/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SharedSharedIdRouteImport } from './routes/shared/$sharedId'
import { Route as FoldersFolderIdRouteImport } from './routes/folders/$folderId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SharedSharedIdRoute = SharedSharedIdRouteImport.update({
  id: '/shared/$sharedId',
  path: '/shared/$sharedId',
  getParentRoute: () => rootRouteImport,
} as any)
const FoldersFolderIdRoute = FoldersFolderIdRouteImport.update({
  id: '/folders/$folderId',
  path: '/folders/$folderId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/folders/$folderId': typeof FoldersFolderIdRoute
  '/shared/$sharedId': typeof SharedSharedIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/folders/$folderId': typeof FoldersFolderIdRoute
  '/shared/$sharedId': typeof SharedSharedIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/folders/$folderId': typeof FoldersFolderIdRoute
  '/shared/$sharedId': typeof SharedSharedIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/folders/$folderId' | '/shared/$sharedId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/folders/$folderId' | '/shared/$sharedId'
  id: '__root__' | '/' | '/login' | '/folders/$folderId' | '/shared/$sharedId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  FoldersFolderIdRoute: typeof FoldersFolderIdRoute
  SharedSharedIdRoute: typeof SharedSharedIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shared/$sharedId': {
      id: '/shared/$sharedId'
      path: '/shared/$sharedId'
      fullPath: '/shared/$sharedId'
      preLoaderRoute: typeof SharedSharedIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/folders/$folderId': {
      id: '/folders/$folderId'
      path: '/folders/$folderId'
      fullPath: '/folders/$folderId'
      preLoaderRoute: typeof FoldersFolderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  FoldersFolderIdRoute: FoldersFolderIdRoute,
  SharedSharedIdRoute: SharedSharedIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
