version: '3'
services:
  app:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: nestjs_server
    ports:
      - 3000:3000
    env_file:
      - ./.env
    depends_on:
      - psql
    restart: always

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: vite_react_app
    ports:
      - 5173:5173
    env_file:
      - ./.env
    restart: always

  psql:
    container_name: postgres
    image: postgres:15
    env_file:
      - ./.env
    environment:
      PG_DATA: /var/lib/postgresql/data
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_SCHEMA: ${POSTGRES_SCHEMA}
      TZ: Europe/Kyiv
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata: